### ISSUE TITLE
Multiple cases of enter filename

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#113]
When using gameimage to create a wine program, there are 3 instances where you are asked to enter a filename. Would just one not suffice at the start and use this through to the end?

**Comment by ruanformigoni** [comment]
The first one in the wizard is for the game itself, since you can have multiple games you need to enter each name. The second time is for the name as it appears in the desktop entry. The third one is the actual file name, maybe I can auto-complete the file name from the name from the desktop entry, but each of these instances serves a different purpose.

**Comment by Blad3forc3** [comment]
Fair enough Ruan. It just feels like you are entering the name a lot :D

**Comment by ruanformigoni** [comment]
Yes, it is a bit annoying :sweat_smile:
