### ISSUE TITLE
Option to install Older wine versions

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#4]
During the wine appimage process, could an option to download any version of wine from the old 1.0 versions to the present day and use that wine version within the appimage?

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3, thanks for the suggestion, you can choose different wine distributions [here](https://gitlab.com/formigoni/gameimage#select-wine-distribution), versioning would be a more complicated matter. Only in recent versions of wine you can run win32 apps without having 32-bit glibc installed no your system, since the project has the goal to make a game work is several distros, this would introduce an issue that most users would have trouble to solve.

**Comment by ruanformigoni** [comment]
> Only in recent versions of wine you can run win32 apps without having 32-bit glibc installed no your system

Sidenote on this, on flatimage this is not an issue anymore, I'll include Kron4ek wine builds starting from 5.5.

**Comment by ruanformigoni** [comment]
Feature implemented, you can use any wine version you want by providing the tarball, with the `wine_custom` option:

![wine-custom](https://github.com/ruanformigoni/gameimage/assets/18180693/a316b0a5-6bb7-44c9-8f63-b73c7b7b7dad)
