### ISSUE TITLE
Flatimage works as expected while Appimage doesn't start (missing runner)

### ISSUE THREAD

**Issue by casasfernando** [ruanformigoni/gameimage#44]
I just came across this project, it looks really good and fits exactly what I was looking for my old games.
While trying it out I tried to pack one of my games in both formats, FlatImage and AppImage, using the same steps and options in the process for both. Yet while trying to build the AppImage, in the configure step, I was asked to install mono in Wine, while this didn't happened while building the FlatImage, not sure why really as I expected both processes to be the same from Wine perspective at least.

I'm building the app package on a laptop running elementary OS 7.1 (Ubuntu 22.04) and for my use case I would really prefer read-only AppImages, so I can sync them once to my gaming PC and my Steam Deck, but then I only have to sync the overlayfs data with the saved games, instead of the whole app package again (which can be several GBs).

FlatImage worked as expected, the launcher works, the game starts, no issues at all, really impressive.
On the other hand AppImage, is having two different issues:

1. Launcher must be disabled, otherwise I get glibc related errors (missing glibc version). I suspect this is caused by the Launcher being created on a newer Linux environment (Arch?). In any case this is not a big deal as I wouldn't really need the launcher.
2. Even after disabling the Launcher with `GIMG_LAUNCHER_DISABLE=1` the AppImage fails to start because the runner (Wine-GE in this case) is missing. I was expecting it to be included in the AppImage, but it seems not. At build time I was asked if I want to include Wine in the AppImage. I first accepted the default of no, and then I tried the build step again answering yes. In both cases I got the following error while trying to run the AppImage:

```
-- Wine runner is missing
-- You can set it with './star-wars---republic-commando.appimage --gameimage-runner=/path/to/wine'
-- The path must be absolute
```

I couldn't find any reference to this in the README.MD file of the repo.

Packaging commands:
- FlatImage: `GIMG_WINE_DIST=ge ./gameimage.run --platform=wine --name="Star Wars - Republic Commando" --dir=$PWD/sw_republic_commando`
- AppImage: `GIMG_PKG_TYPE=AppImage GIMG_WINE_DIST=ge ./gameimage.run --platform=wine --name="Star Wars - Republic Commando" --dir=$PWD/sw_republic_commando`

Some questions:

- ~Is there any reason why the runner is not included in the AppImage while it is in the FlatImage? Is this expected?~
- Would the AppImage method continue to be maintained moving forward or only FlatImage?
- Would it be possible to have the best of both packages and have read-only FlatImages (still using overlayfs for changing data like saved games, etc)?

Thanks

**Comment by casasfernando** [comment]
I tried the AppImage build process again from scratch, and this time selected to include Wine in the AppImage. It worked.
I think there is a bug, in that if you try to run the build step (4) again, without starting over the process, it doesn't matter if you choose to include Wine or not, it will not be included.

One thing I noticed is that while the AppImage is running in the .config directory that is created in the same directory as the AppImage there is a directory called `wine` that is taking a lot of disk space (3GB in my case) and that is cleaned up when the AppImage stops running. Is this necessary? Can't this be created in a different path like `/tmp`?

**Comment by ruanformigoni** [comment]
Hi @casasfernando , thanks for checking out the project!

> I would really prefer read-only AppImages, so I can sync them once to my gaming PC and my Steam Deck, but then I only have to sync the overlayfs data with the saved games, instead of the whole app package again (which can be several GBs).

Not sure if I understood corretly, but for flatimage, you only require to sync the .my-game.flatimage.config directory, which will contain your saves & other data. Same as it would be for AppImage.

> Would the AppImage method continue to be maintained moving forward or only FlatImage?

AppImage will be completely dropped in the next version, it does not allow the project to achieve its portability goal.

> Would it be possible to have the best of both packages and have read-only FlatImages (still using overlayfs for changing data like saved games, etc)?

Flatimage is not read-only, but game data is already stored in the overlayfs directory. So from what I understood it already does what you expect.

> One thing I noticed is that while the AppImage is running in the .config directory that is created in the same directory as the AppImage there is a directory called wine that is taking a lot of disk space (3GB in my case) and that is cleaned up when the AppImage stops running. Is this necessary?

The image is mounted to /tmp, and the overlayfs mountpoint is set to the .my-game.AppImage.config/wine directory, this allows the changes that are made by the game (creating and modifying save data) to persist in .my-game.AppImage.config/union after the game is closed. The mountpoint was chosen to be in this configuration directory because some applications do not allow running under /tmp.

The project is due to a complete revamp, now with a completely GUI oriented creation process see the [cpp](https://github.com/ruanformigoni/gameimage/tree/cpp) branch. If you'd like to try it out, I have a preview version in [here](https://drive.google.com/file/d/1kfgKoCxTAnxBtwr7LvN9RN829X3Bh_Az/view?usp=sharing).

**Comment by casasfernando** [comment]
Thanks for your replies @ruanformigoni !

Regarding Flatimage behavior, after each execution, although the size remains the same, the modify and change times of the file doesn't.

This will cause the sync client to detect the changes and sync the Flatimage file again with the server and the rest of the clients.
I guess I can do an exclusion on the sync client to ignore Flatimages based on the extension (.flatimage) but then I will have to manually apply the same configuration change and copy the Flatimage files to each machine as needed (not really a big deal)
This is why I was wondering if there could be anyway for the Flatimage files to be read-only as AppImages.

BTW I tried to change permissions on the Flatimage file to only read+execute, but then it doesn't work.
Out of curiosity, if using overlayfs as with the AppImage files for any changed file in the image, why does the Flatimage file needs to be writable? Is it because of the launcher? And if yes, would it be possible to add an option (e.g.: using an env var) to not include the launcher at all in the image (also will prevent having to pass `GIMG_LAUNCHER_DISABLE=1` on each execution)?

**Comment by ruanformigoni** [comment]
Ah I see, at this time flatimage does not support read-only execution. The flatimage file contains the mutable filesystem that is mounted to `/tmp/fim/instance/...`, it is mounted as r/w, so that is probably why r+x resulted in a failure. Even with the launcher disabled, without proper handling it will fail. For example, these are the mountpoints used when running `amnesia-a-machine-for-pigs`:
```
/tmp/fim/instance/71cf41a_20240323223540/mount/BOoBDm.mount.dwarfs.amnesia-a-machine-for-pigs
/tmp/fim/instance/71cf41a_20240323223540/mount/BOoBDm.mount.dwarfs.opt
/tmp/fim/instance/71cf41a_20240323223540/mount/BOoBDm.mount.dwarfs.usr
/tmp/fim/instance/71cf41a_20240323223540/mount/BOoBDm.mount.overlayfs.amnesia-a-machine-for-pigs
/tmp/fim/instance/71cf41a_20240323223540/mount/BOoBDm.mount.overlayfs.usr
```
Symlinks for these mountpoints are created inside the flatimage, which requires it to be writteable, the mount points cannot be created directly inside the mutable filesystem because fuse does not allow it by default.

**Comment by ruanformigoni** [comment]
Project rework released here on github, I'll close the issue since AppImage support was dropped. Feel free to continue the conversation or open another issue :smile:
