### ISSUE TITLE
Command line only / Non GUI Options

### ISSUE THREAD

**Issue by darthcircuit** [ruanformigoni/gameimage#70]
Hello! I just got a new job so i've been out of the loop on the app since about ~.6

I used to exclusively just use the command line options as it's easier for me, but i'm noticing that doesnt seem to be possible anymore? I also see that your gitlab page and the old versions are also missing now.

Are all the options we used to have completely gone now? I really liked being able to choose appimage or flatimage. One reason is because i like having a clean appimage to backup or diagnose with. I like the r/w option of the flatimage, but having an immutable working appimage that i can work with is desirable occasionally too. I also liked being able to disable the launcher directly in the appimage run file.

If it's not possible to have the options we used to in the current versions, that's fine, but will you please re-release the older versions so that I can build my appimages the old way? Thanks!!

**Comment by ruanformigoni** [comment]
Hi @darthcircuit! I have switched the project to use a GUI oriented method to be more accessible to people without knowledge of the linux command line. The gitlab page is temporarily disabled while I sync to be like it is on github, if you have an specific option missing on the previous cli version that you'd like to see on the GUI let me know.

I have moved away from appimage because making portable applications on was not trivial (or possible) on some cases, which does not fit the goal of the project. Moreover maintaining and testing both flatimage and appimage methods would be unfeasible. That said I can try to work on a read-only method for flatimage, which would be useful to use with file sync clients to avoid unnecessary copies like @Tell-Sackett has mentioned.

Besides the read-only feature, let me know of other features you'd like to see possible on the project when compared to the `0.x` versions.
