### ISSUE TITLE
Fedora Silverblue - error creating symlinks on configurations

### ISSUE THREAD

**Issue by darthcircuit** [ruanformigoni/gameimage#71]
Hi Ruan!

My current laptop is running fedora silverblue and upon trying to build a wine flatimage, i'm greeted with this message in the logs on any action that starts wine:

I :: [e] :: ln: failed to create symbolic link '/run/media/john/Untitled/xwa/build/.wine.flatimage.config/overlays/usr/mount': Operation not permitted

I haven't tested building any other platforms besides wine, but I'm assuming that they will be the same issue. Silverblue has an immutable root partition and so some things act weird, so i'm assuming that's what's happening here. Do you know of anything i can try?

**Comment by ruanformigoni** [comment]
Hi @darthcircuit, thanks for reporting this issue! Could you try it from inside your home directory, to see if it is a permission issue with the external hard-drive?

**Comment by darthcircuit** [comment]
Good catch! I tried again in my home folder and it worked. Thanks!

**Comment by ruanformigoni** [comment]
No problem! Do you know if the paths `/run/media/john/Untitled` or `/run/media/john/Untitled/xwa/` are or have a symlink to somewhere else? I've installed silverblue and could not replicate this issue (I tried with an internal and usb drives). Could you tell me about what the gnome disks utility shows when you click on your drive -> additional partition options (the gear icon) -> edit mount options? This issue is probably related with a missing binding in flatimage, but I could not pinpoint where it is yet. Thanks!

**Comment by darthcircuit** [comment]
My mistake was that the folder I was running from was an external hard drive that was formatted ntfs, which I'm pretty sure that fuse doesn't play nicely with.

**Comment by ruanformigoni** [comment]
Got it! Thanks a lot for getting back on this, I'll try to add a warning about ntfs. Anything else feel free to re-open the issue :smile:
